name: Hello World workflow 
on: 
   push:
       branches: main
   pull_request:
       branches: main
   workflow_dispatch:
jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
         - name : Checkout repository
           uses :  actions/checkout@v2
         - name : setup node
           uses : actions/setup-node@v3
           with :
            node-version : 18
         - name : Go to client directory 
           run : cd Client/urlshortner frontend
         - name : install dep
           run : npm install 
         - name : develop build 
           run : npm run build



